import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Clock3, Database, Search } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";

type GameId = "hsr" | "genshin" | "zzz";
const GAME_LABELS: Record<GameId, string> = { hsr: "HSR", genshin: "原神", zzz: "ZZZ" };

export default function GuideHistory() {
  const history = trpc.build.guideHistory.useQuery();
  const [game, setGame] = useState<"all" | GameId>("all");
  const [query, setQuery] = useState("");
  const characters = useMemo(() => (history.data?.characters ?? []).filter((item) => (game === "all" || item.game === game) && item.name.toLowerCase().includes(query.trim().toLowerCase())), [history.data?.characters, game, query]);

  return <div className="min-h-screen overflow-hidden">
    <header className="container pt-6 sm:pt-8"><div className="flex items-center justify-between border-y border-stone-400 py-3"><div className="flex items-center gap-3"><span className="inline-block h-2 w-2 rounded-full bg-amber-700" /><p className="detail-mono text-[9px] text-stone-600">BUILD GUIDE ARCHIVE</p></div><Link href="/"><Button variant="ghost" size="sm" className="h-8 rounded-none text-[10px] text-stone-600 hover:bg-stone-200"><ArrowLeft className="h-3.5 w-3.5" />照会画面へ</Button></Link></div></header>
    <main className="container pb-20 pt-10 sm:pt-16">
      <section className="max-w-3xl"><p className="detail-mono text-[10px] text-amber-800">CURATION LOG / DATA TIMELINE</p><h1 className="display-serif mt-3 text-5xl font-semibold tracking-[-.045em] sm:text-6xl">更新履歴</h1><p className="mt-5 max-w-2xl font-serif text-base leading-7 text-stone-600">目標ステータスの更新時点、参照範囲、キャラクター別の採用プロファイルを確認できます。履歴は<strong className="font-semibold text-stone-900">現在記録している基準日以降</strong>を表示します。</p></section>
      {history.isLoading && <section className="mt-12 border-y border-stone-300 py-10 text-center"><p className="detail-mono text-[10px] text-stone-500">LOADING CURATION LOG</p></section>}
      {history.data && <>
        <section className="mt-12 grid gap-5 border-y border-stone-400 py-5 sm:grid-cols-3"><article><p className="detail-mono text-[9px] text-stone-500">CURRENT BASELINE</p><p className="mt-2 font-serif text-xl font-semibold">{history.data.currentBaseline} JST</p></article><article><p className="detail-mono text-[9px] text-stone-500">REGISTERED GUIDES</p><p className="mt-2 font-serif text-xl font-semibold">{history.data.characters.length} 件</p></article><article><p className="detail-mono text-[9px] text-stone-500">UPDATE POLICY</p><p className="mt-2 text-sm leading-5 text-stone-700">外部公開ガイドの照合後に、目標値と参照範囲を更新します。</p></article></section>
        <section className="mt-12"><div><p className="detail-mono text-[9px] text-amber-800">SITE-WIDE CHANGES</p><h2 className="display-serif mt-1 text-3xl font-semibold">サイト全体の更新</h2></div><div className="mt-6 space-y-0 border-t border-stone-300">{history.data.siteEvents.map((event) => <article key={`${event.date}-${event.title}`} className="grid gap-3 border-b border-stone-300 py-5 sm:grid-cols-[140px_1fr]"><p className="detail-mono text-[10px] text-amber-800">{event.date} JST</p><div><h3 className="font-serif text-xl font-semibold">{event.title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{event.summary}</p><ul className="mt-3 space-y-1 border-l-2 border-amber-700 pl-3 text-xs leading-5 text-stone-700">{event.changes.map((change) => <li key={change}>{change}</li>)}</ul><p className="mt-3 text-xs leading-5 text-stone-600"><span className="detail-mono mr-2 text-[9px] text-amber-800">RATIONALE</span>{event.rationale}</p><p className="mt-3 detail-mono text-[9px] text-stone-500">{event.games.map((item) => GAME_LABELS[item]).join(" / ")}</p></div></article>)}</div></section>
        <section className="mt-14"><div className="flex flex-col justify-between gap-4 border-b border-stone-400 pb-4 sm:flex-row sm:items-end"><div><p className="detail-mono text-[9px] text-amber-800">CHARACTER RECORDS</p><h2 className="display-serif mt-1 text-3xl font-semibold">キャラクター別更新</h2></div><p className="detail-mono text-[9px] text-stone-500">{characters.length} RECORDS</p></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><div className="flex gap-1 border border-stone-300 bg-stone-100/60 p-1">{(["all", "hsr", "genshin", "zzz"] as const).map((id) => <button key={id} type="button" onClick={() => setGame(id)} className={`min-h-9 px-3 text-[10px] font-semibold ${game === id ? "bg-stone-900 text-stone-50" : "text-stone-600 hover:bg-stone-200"}`}>{id === "all" ? "すべて" : GAME_LABELS[id]}</button>)}</div><div className="relative sm:ml-auto sm:w-72"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-stone-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 rounded-none border-stone-300 bg-transparent pl-9 text-sm shadow-none" placeholder="キャラクター名を検索" /></div></div>
          <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[840px] border-collapse text-left"><thead><tr className="border-y border-stone-400"><th className="py-3 detail-mono text-[9px] font-medium text-stone-500">CHARACTER</th><th className="py-3 detail-mono text-[9px] font-medium text-stone-500">PROFILE</th><th className="py-3 detail-mono text-[9px] font-medium text-stone-500">DATA AS OF</th><th className="py-3 detail-mono text-[9px] font-medium text-stone-500">REFERENCE</th><th className="py-3 detail-mono text-[9px] font-medium text-stone-500">HISTORY</th></tr></thead><tbody>{characters.map((item) => <tr key={`${item.game}-${item.name}`} className="border-b border-stone-200"><td className="py-4"><p className="font-serif text-base font-semibold">{item.name}</p><p className="detail-mono mt-1 text-[9px] text-stone-500">{GAME_LABELS[item.game]}</p></td><td className="py-4 text-sm text-stone-700">{item.profileId}</td><td className="py-4 text-sm text-stone-700">{item.dataAsOf} JST</td><td className="max-w-64 py-4 text-xs leading-5 text-stone-600">{item.sourceLabel}</td><td className="py-4 text-xs leading-5 text-stone-600">{item.events.map((event) => <div key={`${event.date}-${event.title}`} className="mb-3 last:mb-0"><p><Clock3 className="mr-1 inline h-3.5 w-3.5 text-amber-800" />{event.date} / {event.title}</p><p className="mt-1 text-stone-500">{event.changes.join("・")}</p><p className="mt-1 text-stone-500">理由：{event.rationale}</p></div>)}</td></tr>)}</tbody></table></div></section>
      </>}
    </main>
  </div>;
}
