/**
 * 卓球ラバー図鑑 / Court Tempo
 * Design reminder: 初心者〜中級者が「どんな点の取り方をしたいか」から始め、少数の理由付き候補へ迷わず進む。コート線・スコアボード・軌道を選択の進行表示に使う。
 */
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, CircleHelp, RotateCcw, Sparkles, Trophy } from "lucide-react";
import { useMemo, useState } from "react";
import { playStyles, rubbers, sources, type PlayStyle, type Rubber } from "@/lib/rubberData";

type Level = "beginner" | "middle";
type Budget = "easy" | "standard" | "free";

const styleOrder: PlayStyle[] = ["spin", "counter", "control", "defense"];
const stylePhrases: Record<PlayStyle, { headline: string; fore: string; note: string }> = {
  spin: { headline: "回転をかけて、気持ちよく攻めたい。", fore: "回転がかけやすく、弧線で安定して入りやすい候補です。", note: "まずは薄すぎない厚さを選ぶと、ドライブの感覚をつかみやすくなります。" },
  counter: { headline: "早い打点で、相手に押し返したい。", fore: "スピード感とブロックのしやすさを両立する候補です。", note: "硬すぎるラバーよりも、打球感が分かりやすい中程度の硬さから始めましょう。" },
  control: { headline: "ミスを減らして、ラリーを続けたい。", fore: "台上やブロックで扱いやすく、基本技術を積み上げやすい候補です。", note: "最初の一枚は、弾みすぎないラバーがフォームづくりを助けます。" },
  defense: { headline: "守備から、自分のリズムをつくりたい。", fore: "カット・変化・安定感を意識した候補です。", note: "粒高やカット用は技術との相性が大切です。まずはコントロール重視で試しましょう。" },
  sticky: { headline: "強い回転で、相手を動かしたい。", fore: "粘着性を生かした強い回転の候補です。", note: "インパクトが必要なため、基礎ドライブに慣れてからがおすすめです。" },
  shortPips: { headline: "表ソフトで、早い攻撃をしたい。", fore: "ミートとブロックを軸にした表ソフトの候補です。", note: "裏ソフトとは打ち方が変わるため、練習環境と相談して選びましょう。" },
  beginner: { headline: "基本から、自分の得意を見つけたい。", fore: "まずは扱いやすく、基本技術を覚えやすい候補です。", note: "回転とスピードのどちらが楽しいかを感じながら選べます。" },
};

const brandTint: Record<Rubber["brand"], string> = {
  Butterfly: "bg-[#fff0ec] text-[#a53d30]", Nittaku: "bg-[#fceded] text-[#a63d3d]", VICTAS: "bg-[#edf4ff] text-[#28588f]", Yasaka: "bg-[#eff9fb] text-[#26718a]", TIBHAR: "bg-[#eef8f2] text-[#2e7554]", XIOM: "bg-[#fff6e8] text-[#805b20]", STIGA: "bg-[#edf4ff] text-[#245aaa]", DONIC: "bg-[#eef2ff] text-[#2e4d94]", andro: "bg-[#f6efff] text-[#704b9e]",
};

function priceValue(rubber: Rubber) { return rubber.price ?? 10000; }
function matchesBudget(rubber: Rubber, budget: Budget) { return budget === "easy" ? priceValue(rubber) <= 6000 : budget === "standard" ? priceValue(rubber) <= 8000 : true; }
function score(rubber: Rubber, style: PlayStyle, level: Level) {
  const styleFit = rubber.styles.includes(style) ? 20 : 0;
  const beginnerFit = level === "beginner" ? rubber.control * 5 + (rubber.styles.includes("beginner") ? 12 : 0) - Math.max(0, priceValue(rubber) - 7000) / 500 : rubber.control * 2 + rubber.speed + rubber.spin;
  return styleFit + beginnerFit + rubber.speed + rubber.spin;
}

function MiniMeter({ value, label }: { value: number; label: string }) { return <div><div className="mb-1 flex justify-between text-[9px] font-bold tracking-[.08em] text-[#6a7887]"><span>{label}</span><span>{value}</span></div><div className="flex gap-1">{[1,2,3,4,5].map((n) => <i className={`h-1 flex-1 ${n <= value ? "bg-[#c7fa42]" : "bg-[#e5eaee]"}`} key={n} />)}</div></div>; }

export default function Home() {
  const [style, setStyle] = useState<PlayStyle>("spin");
  const [level, setLevel] = useState<Level>("beginner");
  const [budget, setBudget] = useState<Budget>("standard");
  const [showMore, setShowMore] = useState(false);
  const current = playStyles.find((item) => item.id === style) ?? playStyles[0];
  const recommendations = useMemo(() => rubbers.filter((rubber) => rubber.styles.includes(style) && matchesBudget(rubber, budget)).sort((a,b) => score(b, style, level) - score(a, style, level)), [budget, level, style]);
  const featured = recommendations.slice(0, 3);
  const extra = recommendations.slice(3, 9);
  const prompt = stylePhrases[style];
  const reset = () => { setStyle("spin"); setLevel("beginner"); setBudget("standard"); setShowMore(false); };

  return <div className="min-h-screen overflow-x-hidden bg-[#f8faf8] text-[#102c4b] selection:bg-[#c7fa42]">
    <header className="sticky top-0 z-30 border-b border-white/15 bg-[#082a59]/95 text-white backdrop-blur"><div className="mx-auto flex h-[68px] max-w-[1240px] items-center justify-between px-5"><a className="flex items-center gap-3" href="#top"><img src="/manus-storage/rubber-index-mark_9a57d3c9.png" alt="卓球ラバー図鑑" className="h-9 w-9 object-contain" /><span className="font-display text-xl font-black tracking-[-.05em]">RUBBER <span className="text-[#c7fa42]">INDEX</span></span></a><nav className="hidden items-center gap-6 text-[11px] font-black tracking-[.1em] text-[#d6e6f7] sm:flex"><a href="#choose" className="hover:text-[#c7fa42]">スタイルから選ぶ</a><a href="#result" className="hover:text-[#c7fa42]">おすすめ</a><a href="#learn" className="hover:text-[#c7fa42]">選び方</a></nav><a href="#choose" className="bg-[#c7fa42] px-3 py-2 text-[10px] font-black tracking-[.08em] text-[#082a59]">3つの質問で選ぶ</a></div></header>
    <main id="top">
      <section className="relative overflow-hidden bg-[#082a59] text-white"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(rgba(255,255,255,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.09)_1px,transparent_1px)] [background-size:34px_34px]" /><div className="pointer-events-none absolute -right-24 top-10 h-[520px] w-[520px] rounded-full border border-[#c7fa42]/60 shadow-[0_0_0_50px_rgba(199,250,66,.08),0_0_0_100px_rgba(199,250,66,.05)]" /><div className="relative mx-auto grid min-h-[510px] max-w-[1240px] gap-12 px-5 py-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="font-mono text-[10px] font-black tracking-[.16em] text-[#c7fa42]">COURT TEMPO / VERIFIED CHOICE GUIDE / 2026.08</p><h1 className="mt-6 max-w-2xl text-[clamp(3rem,7vw,6.6rem)] font-black leading-[.92] tracking-[-.075em]">プレースタイルから、<br /><span className="text-[#c7fa42]">一枚の選択基準</span>を。</h1><p className="mt-7 max-w-xl text-sm leading-7 text-[#d6e3f2]">回転をかけたい。ラリーを続けたい。早い打点で攻めたい。最初に「得意にしたいこと」を選ぶと、価格・硬度・公式確認情報をもとに候補を絞り込めます。</p><a href="#choose" className="mt-8 inline-flex items-center gap-3 bg-[#c7fa42] px-5 py-3 text-xs font-black tracking-[.08em] text-[#082a59] shadow-[5px_5px_0_#fff] transition hover:-translate-y-0.5 hover:bg-white">選択基準をつくる <ArrowDownRight size={16} /></a></div><div className="relative border border-white/25 bg-[#0c3a74] p-6 shadow-[16px_16px_0_rgba(199,250,66,.18)]"><div className="absolute inset-4 border border-white/15" /><div className="relative"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] font-black tracking-[.14em] text-[#c7fa42]">CHOICE FLOW</p><p className="mt-2 font-black">プレー・予算・根拠の順に読む。</p></div><p className="font-display text-5xl font-black text-[#c7fa42]">01<br /><span className="text-sm text-white">/ 03</span></p></div><div className="mt-16 grid grid-cols-3 gap-3">{[["01","プレースタイル"],["02","レベル"],["03","公式根拠"]].map(([no,label], index) => <div className={`border-t-2 pt-2 ${index === 0 ? "border-[#c7fa42]" : "border-white/30"}`} key={no}><p className={`font-display text-3xl font-black ${index === 0 ? "text-[#c7fa42]" : "text-white"}`}>{no}</p><p className="mt-1 text-[9px] font-bold text-[#c8d8e9]">{label}</p></div>)}</div><p className="mt-7 border-t border-white/15 pt-3 font-mono text-[9px] font-black tracking-[.1em] text-[#c8d8e9]">PRICE / HARDNESS / TYPE / VERIFIED DATE</p></div></div></div></section>
      <section id="choose" className="relative mx-auto max-w-[1240px] overflow-hidden px-5 py-20 [background-image:radial-gradient(rgba(8,42,89,.08)_1px,transparent_1px)] [background-size:18px_18px]"><div className="grid gap-7 border-b border-[#d7e0e7] pb-8 md:grid-cols-[1fr_260px] md:items-end"><div><p className="font-mono text-[10px] font-black tracking-[.14em] text-[#1768db]">STEP 01 / WHAT IS YOUR TEMPO?</p><h2 className="mt-4 text-4xl font-black tracking-[-.055em] md:text-5xl">どんなプレーを、<br />得意にしたいですか？</h2></div><p className="text-sm leading-6 text-[#657487]">正解を当てる必要はありません。今の自分に一番近いものを選んでください。</p></div><div className="mt-7 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{styleOrder.map((id, index) => { const item = playStyles.find((entry) => entry.id === id)!; const active = style === id; return <button key={id} onClick={() => { setStyle(id); setShowMore(false); }} className={`min-h-[176px] border p-5 text-left transition ${active ? "border-[#c7fa42] bg-[#c7fa42] text-[#082a59] shadow-[6px_6px_0_#082a59]" : "border-[#d6e0e7] bg-white hover:-translate-y-1 hover:border-[#082a59]"}`} type="button"><span className={`font-mono text-[10px] font-black ${active ? "text-[#1768db]" : "text-[#1768db]"}`}>0{index+1}</span><strong className="mt-9 block text-lg tracking-[-.04em]">{item.title}</strong><small className={`mt-2 block text-xs leading-5 ${active ? "text-[#294a69]" : "text-[#667587]"}`}>{item.subtitle}</small>{active && <span className="mt-5 inline-flex items-center gap-1 text-[10px] font-black"><Check size={13} /> 選択中</span>}</button>})}</div><div className="mt-10 grid gap-4 border-y border-[#d7e0e7] py-7 md:grid-cols-[1fr_1fr_auto] md:items-center"><ChoiceGroup label="卓球の経験"><ChoiceButton active={level === "beginner"} onClick={() => setLevel("beginner")} title="はじめて〜基礎練習中" /><ChoiceButton active={level === "middle"} onClick={() => setLevel("middle")} title="試合に少し慣れてきた" /></ChoiceGroup><ChoiceGroup label="予算の目安"><ChoiceButton active={budget === "easy"} onClick={() => setBudget("easy")} title="6,000円まで" /><ChoiceButton active={budget === "standard"} onClick={() => setBudget("standard")} title="8,000円まで" /><ChoiceButton active={budget === "free"} onClick={() => setBudget("free")} title="こだわらない" /></ChoiceGroup><button onClick={reset} className="inline-flex items-center gap-2 text-xs font-bold text-[#6c7a88] hover:text-[#082a59]" type="button"><RotateCcw size={14} /> 最初から選ぶ</button></div></section>
      <section id="result" className="relative overflow-hidden bg-[#edf4fa] px-5 py-20 [background-image:linear-gradient(rgba(8,42,89,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(8,42,89,.06)_1px,transparent_1px)] [background-size:30px_30px]"><div className="relative mx-auto max-w-[1240px]"><div className="grid gap-8 md:grid-cols-[1fr_280px] md:items-end"><div><p className="font-mono text-[10px] font-black tracking-[.14em] text-[#1768db]">STEP 02 / VERIFIED RECOMMENDATION</p><h2 className="mt-4 text-4xl font-black tracking-[-.055em] md:text-5xl">{prompt.headline}</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-[#586d82]">{prompt.fore} <strong className="font-black text-[#082a59]">「まずはこれ」</strong>は、いま選んだ条件と公式確認済みの仕様情報をもとに、特に始めやすい一枚です。</p></div><div className="border-l-4 border-[#c7fa42] bg-white p-5"><p className="font-mono text-[10px] font-black tracking-[.12em] text-[#365c82]">SELECTION NOTE</p><p className="mt-2 text-sm font-black leading-6">{prompt.note}</p></div></div><div className="mt-9 grid gap-5 lg:grid-cols-3">{featured.length ? featured.map((rubber, index) => <RecommendationCard rubber={rubber} rank={index} key={rubber.id} />) : <div className="border border-dashed border-[#aebecb] bg-white p-10 text-center lg:col-span-3"><CircleHelp className="mx-auto text-[#627589]" /><p className="mt-4 font-black">この条件では候補が見つかりません。</p><button className="mt-3 text-xs font-bold text-[#0c477b] underline" onClick={() => setBudget("free")} type="button">予算を広げて探す</button></div>}</div>{extra.length > 0 && <div className="mt-8 text-center"><button onClick={() => setShowMore((value) => !value)} className="inline-flex items-center gap-2 border border-[#082a59] bg-white px-5 py-3 text-xs font-black text-[#082a59] transition hover:bg-[#082a59] hover:text-white" type="button">{showMore ? "候補を閉じる" : `ほかの候補も見る（${extra.length}件）`} <ChevronRight className={showMore ? "rotate-90" : ""} size={15} /></button></div>}{showMore && <div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{extra.map((rubber) => <div className="flex items-center justify-between border border-[#d6e0e7] bg-white p-4" key={rubber.id}><div><p className={`inline-block px-1.5 py-0.5 text-[9px] font-black ${brandTint[rubber.brand]}`}>{rubber.brand}</p><p className="mt-2 text-sm font-black">{rubber.name}</p><p className="mt-1 text-[10px] text-[#68788a]">{rubber.priceLabel} / {rubber.hardness} / 公式確認 2026.08</p></div><a href={rubber.source} target="_blank" rel="noreferrer" className="text-[#0c477b]"><ArrowUpRight size={16} /></a></div>)}</div>}</div></section>
      <section id="learn" className="mx-auto max-w-[1240px] px-5 py-20"><div className="grid gap-8 lg:grid-cols-[300px_1fr]"><div><p className="font-mono text-[10px] font-black tracking-[.14em] text-[#ff6756]">FOR YOUR FIRST CHOICE</p><h2 className="mt-4 text-4xl font-black tracking-[-.055em]">迷ったときの、<br />3つの基本。</h2></div><div className="grid gap-px border border-[#d7e0e7] bg-[#d7e0e7] md:grid-cols-3"><Tip no="01" title="まずは硬すぎないもの" text="打球感が分かりやすく、回転をかける練習につながります。" /><Tip no="02" title="予算は両面で考える" text="ラバーは通常2枚使います。最初は扱いやすさを優先しましょう。" /><Tip no="03" title="迷ったらコントロール" text="ラリーが続くと、卓球はもっと楽しくなります。" /></div></div></section>
    </main>
    <footer className="bg-[#082a59] px-5 py-10 text-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="font-display text-2xl font-black">RUBBER <span className="text-[#c7fa42]">INDEX</span></p><p className="mt-3 max-w-xl text-xs leading-5 text-[#c7d7e9]">価格・種別・公式説明はメーカー公式ページを参照しています。価格改定や仕様変更の可能性があるため、購入前に各公式情報をご確認ください。</p></div><div><p className="font-mono text-[10px] font-black tracking-[.12em] text-[#c7fa42]">OFFICIAL SOURCES</p><div className="mt-3 flex max-w-xl flex-wrap gap-x-4 gap-y-2">{sources.slice(0, 6).map((source) => <a className="text-[10px] font-bold text-white hover:text-[#c7fa42]" href={source.url} target="_blank" rel="noreferrer" key={source.name}>{source.name} <ArrowUpRight className="inline" size={11} /></a>)}</div></div></div></footer>
  </div>;
}

function ChoiceGroup({ label, children }: { label: string; children: React.ReactNode }) { return <div><p className="mb-3 font-mono text-[10px] font-black tracking-[.11em] text-[#496177]">{label}</p><div className="flex flex-wrap gap-2">{children}</div></div>; }
function ChoiceButton({ active, onClick, title }: { active: boolean; onClick: () => void; title: string }) { return <button onClick={onClick} className={`border px-3 py-2 text-[11px] font-black transition ${active ? "border-[#c7fa42] bg-[#c7fa42] text-[#082a59] shadow-[inset_0_-3px_0_#082a59]" : "border-[#cbd7e0] bg-white text-[#53687b] hover:border-[#082a59]"}`} type="button">{title}</button>; }
function RecommendationCard({ rubber, rank }: { rubber: Rubber; rank: number }) { const beginner = rank === 0; return <article className={`relative overflow-hidden border bg-white p-6 transition hover:-translate-y-1 ${beginner ? "border-[#c7fa42] shadow-[8px_8px_0_#082a59]" : "border-[#d6e0e7]"}`}><div className="absolute left-0 top-0 h-1 w-full bg-[#c7fa42]" /><div className="flex items-start justify-between gap-3"><div>{beginner && <span className="inline-flex items-center gap-1 bg-[#c7fa42] px-2 py-1 text-[9px] font-black tracking-[.08em] text-[#082a59]"><Trophy size={11} /> まずはこれ</span>}<p className={`${beginner ? "mt-4" : "mt-0"} inline-block px-2 py-1 text-[9px] font-black tracking-[.08em] ${brandTint[rubber.brand]}`}>{rubber.brand}</p></div><span className="font-display text-4xl font-black text-[#d6e0e7]">0{rank+1}</span></div><p className="mt-5 font-mono text-[9px] font-black tracking-[.1em] text-[#2f7650]">VERIFIED SPEC / 2026.08</p><h3 className="mt-2 text-2xl font-black leading-[1.05] tracking-[-.05em]">{rubber.name}</h3><p className="mt-3 min-h-10 text-xs leading-5 text-[#617184]">{rubber.suitableFor}</p><div className="my-6 grid grid-cols-3 gap-3 border-y border-[#e1e7eb] py-4"><MiniMeter value={rubber.speed} label="SPEED" /><MiniMeter value={rubber.spin} label="SPIN" /><MiniMeter value={rubber.control} label="EASY" /></div><div className="border-l-2 border-[#c7fa42] pl-3"><p className="text-[9px] font-black tracking-[.1em] text-[#718092]">OFFICIAL DATA / PRICE · HARDNESS · TYPE</p><div className="mt-2 flex items-end justify-between gap-3"><div><p className="text-sm font-black tabular-nums">{rubber.priceLabel}</p><p className="mt-1 text-xs font-bold text-[#2e6b47]">{rubber.hardness} / {rubber.type}</p></div><a className="inline-flex items-center gap-1 text-[10px] font-black text-[#0c477b] underline underline-offset-4" href={rubber.source} target="_blank" rel="noreferrer">公式を見る <ArrowUpRight size={13} /></a></div></div></article>; }
function Tip({ no, title, text }: { no: string; title: string; text: string }) { return <article className="relative overflow-hidden bg-[#f8faf8] p-6"><span className="absolute left-0 top-0 h-full w-1 bg-[#c7fa42]" /><p className="font-mono text-[10px] font-black text-[#1768db]">{no}</p><h3 className="mt-9 text-lg font-black tracking-[-.04em]">{title}</h3><p className="mt-3 text-xs leading-6 text-[#68788a]">{text}</p></article>; }
